import React from "react";
import logo from "./logo.svg";
import Form from "./components/Form";
import ForecastCard from "./components/ForecastCard";
import "./App.css";

function App() {
  return (
    <div className="App">
      <Form />
      <div className="cardwrapper">
        {data.forecast.forecastday.map((elem) => (
          <ForecastCard data={elem} />
        ))}
      </div>
    </div>
  );
}

export default App;

const data = {
  location: {
    name: "Shinjuku",
    region: "Kanagawa",
    country: "Japan",
    lat: 35.29,
    lon: 139.57,
    tz_id: "Australia/Melbourne",
    localtime_epoch: 1601517508,
    localtime: "2020-10-01 11:58",
  },
  current: {
    last_updated_epoch: 1601509512,
    last_updated: "2020-10-01 09:45",
    temp_c: 19.0,
    temp_f: 66.2,
    is_day: 1,
    condition: {
      text: "Light rain",
      icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
      code: 1183,
    },
    wind_mph: 4.3,
    wind_kph: 6.8,
    wind_degree: 10,
    wind_dir: "N",
    pressure_mb: 1010.0,
    pressure_in: 30.3,
    precip_mm: 0.6,
    precip_in: 0.02,
    humidity: 94,
    cloud: 75,
    feelslike_c: 19.0,
    feelslike_f: 66.2,
    vis_km: 8.0,
    vis_miles: 4.0,
    uv: 4.0,
    gust_mph: 8.3,
    gust_kph: 13.3,
  },
  forecast: {
    forecastday: [
      {
        date: "2020-10-01",
        date_epoch: 1601510400,
        day: {
          maxtemp_c: 20.6,
          maxtemp_f: 69.1,
          mintemp_c: 13.6,
          mintemp_f: 56.5,
          avgtemp_c: 19.1,
          avgtemp_f: 66.4,
          maxwind_mph: 13.0,
          maxwind_kph: 20.9,
          totalprecip_mm: 3.1,
          totalprecip_in: 0.12,
          avgvis_km: 9.1,
          avgvis_miles: 5.0,
          avghumidity: 75.0,
          daily_will_it_rain: 1,
          daily_chance_of_rain: "95",
          daily_will_it_snow: 0,
          daily_chance_of_snow: "0",
          condition: {
            text: "Moderate or heavy rain shower",
            icon: "//cdn.weatherapi.com/weather/64x64/day/356.png",
            code: 1243,
          },
          uv: 3.0,
        },
        astro: {
          sunrise: "05:36 AM",
          sunset: "05:26 PM",
          moonrise: "05:28 PM",
          moonset: "04:38 AM",
          moon_phase: "Full Moon",
          moon_illumination: "97",
        },
        hour: [
          {
            time_epoch: 1601474400,
            time: "2020-10-01 00:00",
            temp_c: 21.4,
            temp_f: 70.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 86,
            wind_dir: "E",
            pressure_mb: 1009.0,
            pressure_in: 30.3,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 71,
            cloud: 50,
            feelslike_c: 21.4,
            feelslike_f: 70.5,
            windchill_c: 21.4,
            windchill_f: 70.5,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.7,
          },
          {
            time_epoch: 1601478000,
            time: "2020-10-01 01:00",
            temp_c: 21.3,
            temp_f: 70.3,
            is_day: 0,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/263.png",
              code: 1150,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 74,
            wind_dir: "ENE",
            pressure_mb: 1009.0,
            pressure_in: 30.3,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 72,
            cloud: 53,
            feelslike_c: 21.3,
            feelslike_f: 70.3,
            windchill_c: 21.3,
            windchill_f: 70.3,
            heatindex_c: 23.3,
            heatindex_f: 73.9,
            dewpoint_c: 16.0,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: "18",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 8.3,
            vis_miles: 5.0,
            gust_mph: 10.5,
            gust_kph: 16.9,
          },
          {
            time_epoch: 1601481600,
            time: "2020-10-01 02:00",
            temp_c: 21.1,
            temp_f: 70.0,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 61,
            wind_dir: "ENE",
            pressure_mb: 1009.0,
            pressure_in: 30.3,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 73,
            cloud: 56,
            feelslike_c: 21.1,
            feelslike_f: 70.0,
            windchill_c: 21.1,
            windchill_f: 70.0,
            heatindex_c: 22.1,
            heatindex_f: 71.8,
            dewpoint_c: 16.2,
            dewpoint_f: 61.2,
            will_it_rain: 0,
            chance_of_rain: "37",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 6.7,
            vis_miles: 4.0,
            gust_mph: 9.4,
            gust_kph: 15.1,
          },
          {
            time_epoch: 1601485200,
            time: "2020-10-01 03:00",
            temp_c: 21.0,
            temp_f: 69.8,
            is_day: 0,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/263.png",
              code: 1150,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 49,
            wind_dir: "NE",
            pressure_mb: 1009.0,
            pressure_in: 30.3,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 75,
            cloud: 58,
            feelslike_c: 21.0,
            feelslike_f: 69.8,
            windchill_c: 21.0,
            windchill_f: 69.8,
            heatindex_c: 21.0,
            heatindex_f: 69.8,
            dewpoint_c: 16.3,
            dewpoint_f: 61.3,
            will_it_rain: 0,
            chance_of_rain: "55",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 5.0,
            vis_miles: 3.0,
            gust_mph: 8.3,
            gust_kph: 13.3,
          },
          {
            time_epoch: 1601488800,
            time: "2020-10-01 04:00",
            temp_c: 20.6,
            temp_f: 69.1,
            is_day: 0,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
              code: 1183,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 56,
            wind_dir: "ENE",
            pressure_mb: 1009.0,
            pressure_in: 30.3,
            precip_mm: 0.9,
            precip_in: 0.04,
            humidity: 77,
            cloud: 67,
            feelslike_c: 20.6,
            feelslike_f: 69.1,
            windchill_c: 20.6,
            windchill_f: 69.1,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 16.5,
            dewpoint_f: 61.7,
            will_it_rain: 0,
            chance_of_rain: "65",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 6.3,
            vis_miles: 3.0,
            gust_mph: 8.1,
            gust_kph: 13.0,
          },
          {
            time_epoch: 1601492400,
            time: "2020-10-01 05:00",
            temp_c: 20.3,
            temp_f: 68.5,
            is_day: 0,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/263.png",
              code: 1150,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 62,
            wind_dir: "ENE",
            pressure_mb: 1009.0,
            pressure_in: 30.3,
            precip_mm: 1.4,
            precip_in: 0.06,
            humidity: 80,
            cloud: 76,
            feelslike_c: 20.3,
            feelslike_f: 68.5,
            windchill_c: 20.3,
            windchill_f: 68.5,
            heatindex_c: 20.3,
            heatindex_f: 68.5,
            dewpoint_c: 16.6,
            dewpoint_f: 61.9,
            will_it_rain: 1,
            chance_of_rain: "75",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 7.7,
            vis_miles: 4.0,
            gust_mph: 7.8,
            gust_kph: 12.6,
          },
          {
            time_epoch: 1601496000,
            time: "2020-10-01 06:00",
            temp_c: 19.9,
            temp_f: 67.8,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 69,
            wind_dir: "ENE",
            pressure_mb: 1009.0,
            pressure_in: 30.3,
            precip_mm: 1.9,
            precip_in: 0.07,
            humidity: 82,
            cloud: 85,
            feelslike_c: 19.9,
            feelslike_f: 67.8,
            windchill_c: 19.9,
            windchill_f: 67.8,
            heatindex_c: 19.9,
            heatindex_f: 67.8,
            dewpoint_c: 16.8,
            dewpoint_f: 62.2,
            will_it_rain: 1,
            chance_of_rain: "84",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 7.6,
            gust_kph: 12.2,
          },
          {
            time_epoch: 1601499600,
            time: "2020-10-01 07:00",
            temp_c: 19.7,
            temp_f: 67.5,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 63,
            wind_dir: "ENE",
            pressure_mb: 1009.0,
            pressure_in: 30.3,
            precip_mm: 1.3,
            precip_in: 0.05,
            humidity: 80,
            cloud: 90,
            feelslike_c: 19.7,
            feelslike_f: 67.5,
            windchill_c: 19.7,
            windchill_f: 67.5,
            heatindex_c: 19.7,
            heatindex_f: 67.5,
            dewpoint_c: 16.1,
            dewpoint_f: 61.0,
            will_it_rain: 0,
            chance_of_rain: "56",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.3,
            vis_miles: 5.0,
            gust_mph: 8.1,
            gust_kph: 13.0,
          },
          {
            time_epoch: 1601503200,
            time: "2020-10-01 08:00",
            temp_c: 19.5,
            temp_f: 67.1,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 57,
            wind_dir: "ENE",
            pressure_mb: 1010.0,
            pressure_in: 30.3,
            precip_mm: 0.6,
            precip_in: 0.02,
            humidity: 77,
            cloud: 94,
            feelslike_c: 19.5,
            feelslike_f: 67.1,
            windchill_c: 19.5,
            windchill_f: 67.1,
            heatindex_c: 19.5,
            heatindex_f: 67.1,
            dewpoint_c: 15.5,
            dewpoint_f: 59.9,
            will_it_rain: 0,
            chance_of_rain: "28",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.7,
            vis_miles: 6.0,
            gust_mph: 8.3,
            gust_kph: 13.3,
          },
          {
            time_epoch: 1601506800,
            time: "2020-10-01 09:00",
            temp_c: 19.3,
            temp_f: 66.7,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 51,
            wind_dir: "NE",
            pressure_mb: 1010.0,
            pressure_in: 30.3,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 75,
            cloud: 98,
            feelslike_c: 19.3,
            feelslike_f: 66.7,
            windchill_c: 19.3,
            windchill_f: 66.7,
            heatindex_c: 19.3,
            heatindex_f: 66.7,
            dewpoint_c: 14.8,
            dewpoint_f: 58.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.7,
            gust_kph: 14.0,
          },
          {
            time_epoch: 1601510400,
            time: "2020-10-01 10:00",
            temp_c: 19.4,
            temp_f: 66.9,
            is_day: 1,
            condition: {
              text: "Patchy light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/293.png",
              code: 1180,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 50,
            wind_dir: "NE",
            pressure_mb: 1010.0,
            pressure_in: 30.3,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 77,
            cloud: 84,
            feelslike_c: 19.4,
            feelslike_f: 66.9,
            windchill_c: 19.4,
            windchill_f: 66.9,
            heatindex_c: 19.4,
            heatindex_f: 66.9,
            dewpoint_c: 15.2,
            dewpoint_f: 59.4,
            will_it_rain: 0,
            chance_of_rain: "32",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.7,
            vis_miles: 6.0,
            gust_mph: 10.3,
            gust_kph: 16.6,
          },
          {
            time_epoch: 1601514000,
            time: "2020-10-01 11:00",
            temp_c: 19.4,
            temp_f: 66.9,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 49,
            wind_dir: "NE",
            pressure_mb: 1010.0,
            pressure_in: 30.3,
            precip_mm: 0.5,
            precip_in: 0.02,
            humidity: 78,
            cloud: 69,
            feelslike_c: 19.4,
            feelslike_f: 66.9,
            windchill_c: 19.4,
            windchill_f: 66.9,
            heatindex_c: 19.4,
            heatindex_f: 66.9,
            dewpoint_c: 15.5,
            dewpoint_f: 59.9,
            will_it_rain: 0,
            chance_of_rain: "63",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.3,
            vis_miles: 5.0,
            gust_mph: 12.1,
            gust_kph: 19.4,
          },
          {
            time_epoch: 1601517600,
            time: "2020-10-01 12:00",
            temp_c: 19.5,
            temp_f: 67.1,
            is_day: 1,
            condition: {
              text: "Patchy light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/293.png",
              code: 1180,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 47,
            wind_dir: "NE",
            pressure_mb: 1010.0,
            pressure_in: 30.3,
            precip_mm: 0.8,
            precip_in: 0.03,
            humidity: 80,
            cloud: 54,
            feelslike_c: 19.5,
            feelslike_f: 67.1,
            windchill_c: 19.5,
            windchill_f: 67.1,
            heatindex_c: 19.5,
            heatindex_f: 67.1,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 1,
            chance_of_rain: "95",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 13.6,
            gust_kph: 22.0,
          },
          {
            time_epoch: 1601521200,
            time: "2020-10-01 13:00",
            temp_c: 19.9,
            temp_f: 67.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 44,
            wind_dir: "NE",
            pressure_mb: 1010.0,
            pressure_in: 30.3,
            precip_mm: 0.5,
            precip_in: 0.02,
            humidity: 79,
            cloud: 49,
            feelslike_c: 19.9,
            feelslike_f: 67.8,
            windchill_c: 19.9,
            windchill_f: 67.8,
            heatindex_c: 19.9,
            heatindex_f: 67.8,
            dewpoint_c: 16.0,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: "63",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.3,
            vis_miles: 5.0,
            gust_mph: 14.5,
            gust_kph: 23.4,
          },
          {
            time_epoch: 1601524800,
            time: "2020-10-01 14:00",
            temp_c: 20.2,
            temp_f: 68.4,
            is_day: 1,
            condition: {
              text: "Patchy light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/293.png",
              code: 1180,
            },
            wind_mph: 12.3,
            wind_kph: 19.8,
            wind_degree: 41,
            wind_dir: "NE",
            pressure_mb: 1010.0,
            pressure_in: 30.3,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 77,
            cloud: 44,
            feelslike_c: 20.2,
            feelslike_f: 68.4,
            windchill_c: 20.2,
            windchill_f: 68.4,
            heatindex_c: 20.2,
            heatindex_f: 68.4,
            dewpoint_c: 16.2,
            dewpoint_f: 61.2,
            will_it_rain: 0,
            chance_of_rain: "32",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.7,
            vis_miles: 6.0,
            gust_mph: 15.7,
            gust_kph: 25.2,
          },
          {
            time_epoch: 1601528400,
            time: "2020-10-01 15:00",
            temp_c: 20.6,
            temp_f: 69.1,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 13.0,
            wind_kph: 20.9,
            wind_degree: 38,
            wind_dir: "NE",
            pressure_mb: 1010.0,
            pressure_in: 30.3,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 76,
            cloud: 38,
            feelslike_c: 20.6,
            feelslike_f: 69.1,
            windchill_c: 20.6,
            windchill_f: 69.1,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 16.3,
            dewpoint_f: 61.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.6,
            gust_kph: 26.6,
          },
          {
            time_epoch: 1601532000,
            time: "2020-10-01 16:00",
            temp_c: 19.6,
            temp_f: 67.3,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 12.3,
            wind_kph: 19.8,
            wind_degree: 40,
            wind_dir: "NE",
            pressure_mb: 1011.0,
            pressure_in: 30.3,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 74,
            cloud: 35,
            feelslike_c: 19.6,
            feelslike_f: 67.3,
            windchill_c: 19.6,
            windchill_f: 67.3,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 16.2,
            dewpoint_f: 61.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.7,
            gust_kph: 25.2,
          },
          {
            time_epoch: 1601535600,
            time: "2020-10-01 17:00",
            temp_c: 18.6,
            temp_f: 65.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 41,
            wind_dir: "NE",
            pressure_mb: 1011.0,
            pressure_in: 30.3,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 72,
            cloud: 32,
            feelslike_c: 18.6,
            feelslike_f: 65.5,
            windchill_c: 18.6,
            windchill_f: 65.5,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 16.1,
            dewpoint_f: 61.0,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.5,
            gust_kph: 23.4,
          },
          {
            time_epoch: 1601539200,
            time: "2020-10-01 18:00",
            temp_c: 17.6,
            temp_f: 63.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 43,
            wind_dir: "NE",
            pressure_mb: 1012.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 29,
            feelslike_c: 17.6,
            feelslike_f: 63.7,
            windchill_c: 17.6,
            windchill_f: 63.7,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 16.0,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.6,
            gust_kph: 22.0,
          },
          {
            time_epoch: 1601542800,
            time: "2020-10-01 19:00",
            temp_c: 16.3,
            temp_f: 61.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 11.2,
            wind_kph: 18.0,
            wind_degree: 43,
            wind_dir: "NE",
            pressure_mb: 1012.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 71,
            cloud: 31,
            feelslike_c: 16.3,
            feelslike_f: 61.3,
            windchill_c: 16.3,
            windchill_f: 61.3,
            heatindex_c: 18.9,
            heatindex_f: 66.0,
            dewpoint_c: 16.0,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.3,
            gust_kph: 23.0,
          },
          {
            time_epoch: 1601546400,
            time: "2020-10-01 20:00",
            temp_c: 14.9,
            temp_f: 58.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 42,
            wind_dir: "NE",
            pressure_mb: 1013.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 71,
            cloud: 34,
            feelslike_c: 14.9,
            feelslike_f: 58.8,
            windchill_c: 14.9,
            windchill_f: 58.8,
            heatindex_c: 17.3,
            heatindex_f: 63.1,
            dewpoint_c: 16.0,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.8,
            gust_kph: 23.8,
          },
          {
            time_epoch: 1601550000,
            time: "2020-10-01 21:00",
            temp_c: 13.6,
            temp_f: 56.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 11.9,
            wind_kph: 19.1,
            wind_degree: 41,
            wind_dir: "NE",
            pressure_mb: 1013.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 72,
            cloud: 36,
            feelslike_c: 13.6,
            feelslike_f: 56.5,
            windchill_c: 13.6,
            windchill_f: 56.5,
            heatindex_c: 15.6,
            heatindex_f: 60.1,
            dewpoint_c: 16.0,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.4,
            gust_kph: 24.8,
          },
          {
            time_epoch: 1601553600,
            time: "2020-10-01 22:00",
            temp_c: 16.1,
            temp_f: 61.0,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 41,
            wind_dir: "NE",
            pressure_mb: 1014.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 73,
            cloud: 27,
            feelslike_c: 16.1,
            feelslike_f: 61.0,
            windchill_c: 16.1,
            windchill_f: 61.0,
            heatindex_c: 18.5,
            heatindex_f: 65.3,
            dewpoint_c: 16.1,
            dewpoint_f: 61.0,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.8,
            gust_kph: 23.8,
          },
          {
            time_epoch: 1601557200,
            time: "2020-10-01 23:00",
            temp_c: 18.6,
            temp_f: 65.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 11.2,
            wind_kph: 18.0,
            wind_degree: 41,
            wind_dir: "NE",
            pressure_mb: 1014.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 73,
            cloud: 19,
            feelslike_c: 18.6,
            feelslike_f: 65.5,
            windchill_c: 18.6,
            windchill_f: 65.5,
            heatindex_c: 21.5,
            heatindex_f: 70.7,
            dewpoint_c: 16.2,
            dewpoint_f: 61.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.9,
            gust_kph: 22.3,
          },
        ],
      },
      {
        date: "2020-10-02",
        date_epoch: 1601596800,
        day: {
          maxtemp_c: 24.4,
          maxtemp_f: 75.9,
          mintemp_c: 20.5,
          mintemp_f: 68.9,
          avgtemp_c: 21.8,
          avgtemp_f: 71.3,
          maxwind_mph: 10.7,
          maxwind_kph: 17.3,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 69.0,
          daily_will_it_rain: 0,
          daily_chance_of_rain: "0",
          daily_will_it_snow: 0,
          daily_chance_of_snow: "0",
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          uv: 6.0,
        },
        astro: {
          sunrise: "05:37 AM",
          sunset: "05:24 PM",
          moonrise: "05:54 PM",
          moonset: "05:34 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: "97",
        },
        hour: [
          {
            time_epoch: 1601560800,
            time: "2020-10-02 00:00",
            temp_c: 21.1,
            temp_f: 70.0,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 42,
            wind_dir: "NE",
            pressure_mb: 1014.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 74,
            cloud: 10,
            feelslike_c: 21.1,
            feelslike_f: 70.0,
            windchill_c: 21.1,
            windchill_f: 70.0,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 16.3,
            dewpoint_f: 61.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.2,
            gust_kph: 21.2,
          },
          {
            time_epoch: 1601564400,
            time: "2020-10-02 01:00",
            temp_c: 21.0,
            temp_f: 69.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 40,
            wind_dir: "NE",
            pressure_mb: 1014.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 74,
            cloud: 13,
            feelslike_c: 21.0,
            feelslike_f: 69.8,
            windchill_c: 21.0,
            windchill_f: 69.8,
            heatindex_c: 23.2,
            heatindex_f: 73.8,
            dewpoint_c: 16.2,
            dewpoint_f: 61.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.2,
            gust_kph: 21.2,
          },
          {
            time_epoch: 1601568000,
            time: "2020-10-02 02:00",
            temp_c: 20.8,
            temp_f: 69.4,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 38,
            wind_dir: "NE",
            pressure_mb: 1014.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 74,
            cloud: 16,
            feelslike_c: 20.8,
            feelslike_f: 69.4,
            windchill_c: 20.8,
            windchill_f: 69.4,
            heatindex_c: 21.9,
            heatindex_f: 71.4,
            dewpoint_c: 16.1,
            dewpoint_f: 61.0,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.6,
          },
          {
            time_epoch: 1601571600,
            time: "2020-10-02 03:00",
            temp_c: 20.7,
            temp_f: 69.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 36,
            wind_dir: "NE",
            pressure_mb: 1015.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 74,
            cloud: 20,
            feelslike_c: 20.7,
            feelslike_f: 69.3,
            windchill_c: 20.7,
            windchill_f: 69.3,
            heatindex_c: 20.7,
            heatindex_f: 69.3,
            dewpoint_c: 16.0,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.6,
          },
          {
            time_epoch: 1601575200,
            time: "2020-10-02 04:00",
            temp_c: 20.6,
            temp_f: 69.1,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 38,
            wind_dir: "NE",
            pressure_mb: 1015.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 74,
            cloud: 21,
            feelslike_c: 20.6,
            feelslike_f: 69.1,
            windchill_c: 20.6,
            windchill_f: 69.1,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.6,
          },
          {
            time_epoch: 1601578800,
            time: "2020-10-02 05:00",
            temp_c: 20.6,
            temp_f: 69.1,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 41,
            wind_dir: "NE",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 75,
            cloud: 22,
            feelslike_c: 20.6,
            feelslike_f: 69.1,
            windchill_c: 20.6,
            windchill_f: 69.1,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.6,
          },
          {
            time_epoch: 1601582400,
            time: "2020-10-02 06:00",
            temp_c: 20.5,
            temp_f: 68.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 43,
            wind_dir: "NE",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 75,
            cloud: 23,
            feelslike_c: 20.5,
            feelslike_f: 68.9,
            windchill_c: 20.5,
            windchill_f: 68.9,
            heatindex_c: 20.5,
            heatindex_f: 68.9,
            dewpoint_c: 15.8,
            dewpoint_f: 60.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.6,
          },
          {
            time_epoch: 1601586000,
            time: "2020-10-02 07:00",
            temp_c: 20.6,
            temp_f: 69.1,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 44,
            wind_dir: "NE",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 74,
            cloud: 29,
            feelslike_c: 20.6,
            feelslike_f: 69.1,
            windchill_c: 20.6,
            windchill_f: 69.1,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.8,
            gust_kph: 20.5,
          },
          {
            time_epoch: 1601589600,
            time: "2020-10-02 08:00",
            temp_c: 20.8,
            temp_f: 69.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 44,
            wind_dir: "NE",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 73,
            cloud: 34,
            feelslike_c: 20.8,
            feelslike_f: 69.4,
            windchill_c: 20.8,
            windchill_f: 69.4,
            heatindex_c: 20.8,
            heatindex_f: 69.4,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.3,
            gust_kph: 19.8,
          },
          {
            time_epoch: 1601593200,
            time: "2020-10-02 09:00",
            temp_c: 20.9,
            temp_f: 69.6,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 45,
            wind_dir: "NE",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 72,
            cloud: 40,
            feelslike_c: 20.9,
            feelslike_f: 69.6,
            windchill_c: 20.9,
            windchill_f: 69.6,
            heatindex_c: 20.9,
            heatindex_f: 69.6,
            dewpoint_c: 15.6,
            dewpoint_f: 60.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.7,
          },
          {
            time_epoch: 1601596800,
            time: "2020-10-02 10:00",
            temp_c: 21.4,
            temp_f: 70.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 31,
            wind_dir: "NNE",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 28,
            feelslike_c: 21.4,
            feelslike_f: 70.5,
            windchill_c: 21.4,
            windchill_f: 70.5,
            heatindex_c: 22.2,
            heatindex_f: 72.0,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.1,
            gust_kph: 16.2,
          },
          {
            time_epoch: 1601600400,
            time: "2020-10-02 11:00",
            temp_c: 22.0,
            temp_f: 71.6,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 17,
            wind_dir: "NNE",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 68,
            cloud: 16,
            feelslike_c: 23.5,
            feelslike_f: 74.3,
            windchill_c: 22.0,
            windchill_f: 71.6,
            heatindex_c: 23.5,
            heatindex_f: 74.3,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.7,
            gust_kph: 14.0,
          },
          {
            time_epoch: 1601604000,
            time: "2020-10-02 12:00",
            temp_c: 22.5,
            temp_f: 72.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 3,
            wind_dir: "N",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 67,
            cloud: 3,
            feelslike_c: 24.8,
            feelslike_f: 76.6,
            windchill_c: 22.5,
            windchill_f: 72.5,
            heatindex_c: 24.8,
            heatindex_f: 76.6,
            dewpoint_c: 16.0,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
          },
          {
            time_epoch: 1601607600,
            time: "2020-10-02 13:00",
            temp_c: 23.1,
            temp_f: 73.6,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 73,
            wind_dir: "ENE",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 64,
            cloud: 4,
            feelslike_c: 25.1,
            feelslike_f: 77.2,
            windchill_c: 23.1,
            windchill_f: 73.6,
            heatindex_c: 25.1,
            heatindex_f: 77.2,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.3,
            gust_kph: 10.1,
          },
          {
            time_epoch: 1601611200,
            time: "2020-10-02 14:00",
            temp_c: 23.8,
            temp_f: 74.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 142,
            wind_dir: "SE",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 4,
            feelslike_c: 25.4,
            feelslike_f: 77.7,
            windchill_c: 23.8,
            windchill_f: 74.8,
            heatindex_c: 25.4,
            heatindex_f: 77.7,
            dewpoint_c: 15.8,
            dewpoint_f: 60.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.4,
            gust_kph: 8.6,
          },
          {
            time_epoch: 1601614800,
            time: "2020-10-02 15:00",
            temp_c: 24.4,
            temp_f: 75.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 211,
            wind_dir: "SSW",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 58,
            cloud: 5,
            feelslike_c: 25.7,
            feelslike_f: 78.3,
            windchill_c: 24.4,
            windchill_f: 75.9,
            heatindex_c: 25.7,
            heatindex_f: 78.3,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.5,
            gust_kph: 7.2,
          },
          {
            time_epoch: 1601618400,
            time: "2020-10-02 16:00",
            temp_c: 23.8,
            temp_f: 74.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 181,
            wind_dir: "S",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 11,
            feelslike_c: 25.4,
            feelslike_f: 77.7,
            windchill_c: 23.8,
            windchill_f: 74.8,
            heatindex_c: 25.4,
            heatindex_f: 77.7,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.7,
            gust_kph: 10.8,
          },
          {
            time_epoch: 1601622000,
            time: "2020-10-02 17:00",
            temp_c: 23.2,
            temp_f: 73.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 150,
            wind_dir: "SSE",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 64,
            cloud: 17,
            feelslike_c: 25.1,
            feelslike_f: 77.2,
            windchill_c: 23.2,
            windchill_f: 73.8,
            heatindex_c: 25.1,
            heatindex_f: 77.2,
            dewpoint_c: 16.1,
            dewpoint_f: 61.0,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.2,
            gust_kph: 14.8,
          },
          {
            time_epoch: 1601625600,
            time: "2020-10-02 18:00",
            temp_c: 22.6,
            temp_f: 72.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 120,
            wind_dir: "ESE",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 67,
            cloud: 23,
            feelslike_c: 24.8,
            feelslike_f: 76.6,
            windchill_c: 22.6,
            windchill_f: 72.7,
            heatindex_c: 24.8,
            heatindex_f: 76.6,
            dewpoint_c: 16.3,
            dewpoint_f: 61.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.4,
            gust_kph: 18.4,
          },
          {
            time_epoch: 1601629200,
            time: "2020-10-02 19:00",
            temp_c: 22.4,
            temp_f: 72.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 112,
            wind_dir: "ESE",
            pressure_mb: 1018.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 68,
            cloud: 20,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 22.4,
            windchill_f: 72.3,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 16.2,
            dewpoint_f: 61.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.7,
          },
          {
            time_epoch: 1601632800,
            time: "2020-10-02 20:00",
            temp_c: 22.1,
            temp_f: 71.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 104,
            wind_dir: "ESE",
            pressure_mb: 1018.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 68,
            cloud: 17,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 22.1,
            windchill_f: 71.8,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 16.0,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.7,
          },
          {
            time_epoch: 1601636400,
            time: "2020-10-02 21:00",
            temp_c: 21.9,
            temp_f: 71.4,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 96,
            wind_dir: "E",
            pressure_mb: 1018.0,
            pressure_in: 30.6,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 69,
            cloud: 14,
            feelslike_c: 21.9,
            feelslike_f: 71.4,
            windchill_c: 21.9,
            windchill_f: 71.4,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.9,
            gust_kph: 19.1,
          },
          {
            time_epoch: 1601640000,
            time: "2020-10-02 22:00",
            temp_c: 22.0,
            temp_f: 71.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 86,
            wind_dir: "E",
            pressure_mb: 1018.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 69,
            cloud: 16,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 22.0,
            windchill_f: 71.6,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 16.1,
            dewpoint_f: 61.0,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.6,
            gust_kph: 15.5,
          },
          {
            time_epoch: 1601643600,
            time: "2020-10-02 23:00",
            temp_c: 22.0,
            temp_f: 71.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 75,
            wind_dir: "ENE",
            pressure_mb: 1018.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 19,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 22.0,
            windchill_f: 71.6,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 16.3,
            dewpoint_f: 61.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
          },
        ],
      },
      {
        date: "2020-10-03",
        date_epoch: 1601683200,
        day: {
          maxtemp_c: 23.7,
          maxtemp_f: 74.7,
          mintemp_c: 15.7,
          mintemp_f: 60.3,
          avgtemp_c: 21.6,
          avgtemp_f: 70.9,
          maxwind_mph: 7.8,
          maxwind_kph: 12.6,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 66.0,
          daily_will_it_rain: 0,
          daily_chance_of_rain: "0",
          daily_will_it_snow: 0,
          daily_chance_of_snow: "0",
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          uv: 6.0,
        },
        astro: {
          sunrise: "05:38 AM",
          sunset: "05:23 PM",
          moonrise: "06:20 PM",
          moonset: "06:29 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: "90",
        },
        hour: [
          {
            time_epoch: 1601647200,
            time: "2020-10-03 00:00",
            temp_c: 22.1,
            temp_f: 71.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 65,
            wind_dir: "ENE",
            pressure_mb: 1018.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 71,
            cloud: 22,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 22.1,
            windchill_f: 71.8,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 16.5,
            dewpoint_f: 61.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.9,
            gust_kph: 7.9,
          },
          {
            time_epoch: 1601650800,
            time: "2020-10-03 01:00",
            temp_c: 22.3,
            temp_f: 72.1,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 68,
            wind_dir: "ENE",
            pressure_mb: 1018.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 16,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 22.3,
            windchill_f: 72.1,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 16.6,
            dewpoint_f: 61.9,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.4,
            gust_kph: 8.6,
          },
          {
            time_epoch: 1601654400,
            time: "2020-10-03 02:00",
            temp_c: 22.4,
            temp_f: 72.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 72,
            wind_dir: "ENE",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 11,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 22.4,
            windchill_f: 72.3,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 16.8,
            dewpoint_f: 62.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.0,
            gust_kph: 9.7,
          },
          {
            time_epoch: 1601658000,
            time: "2020-10-03 03:00",
            temp_c: 22.6,
            temp_f: 72.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 75,
            wind_dir: "ENE",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 5,
            feelslike_c: 24.8,
            feelslike_f: 76.6,
            windchill_c: 22.6,
            windchill_f: 72.7,
            heatindex_c: 24.8,
            heatindex_f: 76.6,
            dewpoint_c: 16.9,
            dewpoint_f: 62.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.5,
            gust_kph: 10.4,
          },
          {
            time_epoch: 1601661600,
            time: "2020-10-03 04:00",
            temp_c: 22.4,
            temp_f: 72.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 70,
            wind_dir: "ENE",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 6,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 22.4,
            windchill_f: 72.3,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 16.7,
            dewpoint_f: 62.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.4,
            gust_kph: 11.9,
          },
          {
            time_epoch: 1601665200,
            time: "2020-10-03 05:00",
            temp_c: 22.1,
            temp_f: 71.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 65,
            wind_dir: "ENE",
            pressure_mb: 1018.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 7,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 22.1,
            windchill_f: 71.8,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 16.5,
            dewpoint_f: 61.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.1,
            gust_kph: 13.0,
          },
          {
            time_epoch: 1601668800,
            time: "2020-10-03 06:00",
            temp_c: 21.9,
            temp_f: 71.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 60,
            wind_dir: "ENE",
            pressure_mb: 1018.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 71,
            cloud: 8,
            feelslike_c: 21.9,
            feelslike_f: 71.4,
            windchill_c: 21.9,
            windchill_f: 71.4,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 16.3,
            dewpoint_f: 61.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.9,
            gust_kph: 14.4,
          },
          {
            time_epoch: 1601672400,
            time: "2020-10-03 07:00",
            temp_c: 22.1,
            temp_f: 71.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 56,
            wind_dir: "ENE",
            pressure_mb: 1018.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 69,
            cloud: 8,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 22.1,
            windchill_f: 71.8,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 16.2,
            dewpoint_f: 61.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.3,
            gust_kph: 13.3,
          },
          {
            time_epoch: 1601676000,
            time: "2020-10-03 08:00",
            temp_c: 22.2,
            temp_f: 72.0,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 53,
            wind_dir: "NE",
            pressure_mb: 1018.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 68,
            cloud: 8,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 22.2,
            windchill_f: 72.0,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 16.1,
            dewpoint_f: 61.0,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.8,
            gust_kph: 12.6,
          },
          {
            time_epoch: 1601679600,
            time: "2020-10-03 09:00",
            temp_c: 22.4,
            temp_f: 72.3,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 49,
            wind_dir: "NE",
            pressure_mb: 1018.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 67,
            cloud: 7,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 22.4,
            windchill_f: 72.3,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 16.0,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
          },
          {
            time_epoch: 1601683200,
            time: "2020-10-03 10:00",
            temp_c: 22.6,
            temp_f: 72.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 147,
            wind_dir: "SSE",
            pressure_mb: 1018.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 65,
            cloud: 10,
            feelslike_c: 24.8,
            feelslike_f: 76.6,
            windchill_c: 22.6,
            windchill_f: 72.7,
            heatindex_c: 24.8,
            heatindex_f: 76.6,
            dewpoint_c: 15.8,
            dewpoint_f: 60.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.5,
            gust_kph: 10.4,
          },
          {
            time_epoch: 1601686800,
            time: "2020-10-03 11:00",
            temp_c: 22.7,
            temp_f: 72.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 244,
            wind_dir: "WSW",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 64,
            cloud: 14,
            feelslike_c: 24.8,
            feelslike_f: 76.6,
            windchill_c: 22.7,
            windchill_f: 72.9,
            heatindex_c: 24.8,
            heatindex_f: 76.6,
            dewpoint_c: 15.5,
            dewpoint_f: 59.9,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.0,
            gust_kph: 9.7,
          },
          {
            time_epoch: 1601690400,
            time: "2020-10-03 12:00",
            temp_c: 22.9,
            temp_f: 73.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 342,
            wind_dir: "NNW",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 62,
            cloud: 17,
            feelslike_c: 24.9,
            feelslike_f: 76.8,
            windchill_c: 22.9,
            windchill_f: 73.2,
            heatindex_c: 24.9,
            heatindex_f: 76.8,
            dewpoint_c: 15.3,
            dewpoint_f: 59.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.4,
            gust_kph: 8.6,
          },
          {
            time_epoch: 1601694000,
            time: "2020-10-03 13:00",
            temp_c: 23.2,
            temp_f: 73.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 306,
            wind_dir: "NW",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 18,
            feelslike_c: 25.0,
            feelslike_f: 77.0,
            windchill_c: 23.2,
            windchill_f: 73.8,
            heatindex_c: 25.0,
            heatindex_f: 77.0,
            dewpoint_c: 15.2,
            dewpoint_f: 59.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.7,
            gust_kph: 7.6,
          },
          {
            time_epoch: 1601697600,
            time: "2020-10-03 14:00",
            temp_c: 23.4,
            temp_f: 74.1,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 269,
            wind_dir: "W",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 59,
            cloud: 19,
            feelslike_c: 25.1,
            feelslike_f: 77.2,
            windchill_c: 23.4,
            windchill_f: 74.1,
            heatindex_c: 25.1,
            heatindex_f: 77.2,
            dewpoint_c: 15.0,
            dewpoint_f: 59.0,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.0,
            gust_kph: 6.5,
          },
          {
            time_epoch: 1601701200,
            time: "2020-10-03 15:00",
            temp_c: 23.7,
            temp_f: 74.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 232,
            wind_dir: "SW",
            pressure_mb: 1015.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 58,
            cloud: 20,
            feelslike_c: 25.2,
            feelslike_f: 77.4,
            windchill_c: 23.7,
            windchill_f: 74.7,
            heatindex_c: 25.2,
            heatindex_f: 77.4,
            dewpoint_c: 14.9,
            dewpoint_f: 58.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.4,
            gust_kph: 5.4,
          },
          {
            time_epoch: 1601704800,
            time: "2020-10-03 16:00",
            temp_c: 23.0,
            temp_f: 73.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 201,
            wind_dir: "SSW",
            pressure_mb: 1015.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 59,
            cloud: 15,
            feelslike_c: 25.4,
            feelslike_f: 77.7,
            windchill_c: 23.0,
            windchill_f: 73.4,
            heatindex_c: 25.4,
            heatindex_f: 77.7,
            dewpoint_c: 15.5,
            dewpoint_f: 59.9,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.7,
            gust_kph: 7.6,
          },
          {
            time_epoch: 1601708400,
            time: "2020-10-03 17:00",
            temp_c: 22.4,
            temp_f: 72.3,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 170,
            wind_dir: "S",
            pressure_mb: 1015.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 11,
            feelslike_c: 25.5,
            feelslike_f: 77.9,
            windchill_c: 22.4,
            windchill_f: 72.3,
            heatindex_c: 25.5,
            heatindex_f: 77.9,
            dewpoint_c: 16.1,
            dewpoint_f: 61.0,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.8,
            gust_kph: 9.4,
          },
          {
            time_epoch: 1601712000,
            time: "2020-10-03 18:00",
            temp_c: 21.7,
            temp_f: 71.1,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 139,
            wind_dir: "SE",
            pressure_mb: 1015.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 6,
            feelslike_c: 21.7,
            feelslike_f: 71.1,
            windchill_c: 21.7,
            windchill_f: 71.1,
            heatindex_c: 25.7,
            heatindex_f: 78.3,
            dewpoint_c: 16.7,
            dewpoint_f: 62.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
          },
          {
            time_epoch: 1601715600,
            time: "2020-10-03 19:00",
            temp_c: 19.7,
            temp_f: 67.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 134,
            wind_dir: "SE",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 64,
            cloud: 4,
            feelslike_c: 19.7,
            feelslike_f: 67.5,
            windchill_c: 19.7,
            windchill_f: 67.5,
            heatindex_c: 23.0,
            heatindex_f: 73.4,
            dewpoint_c: 17.4,
            dewpoint_f: 63.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
          },
          {
            time_epoch: 1601719200,
            time: "2020-10-03 20:00",
            temp_c: 17.7,
            temp_f: 63.9,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 130,
            wind_dir: "SE",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 66,
            cloud: 2,
            feelslike_c: 17.7,
            feelslike_f: 63.9,
            windchill_c: 17.7,
            windchill_f: 63.9,
            heatindex_c: 20.4,
            heatindex_f: 68.7,
            dewpoint_c: 18.2,
            dewpoint_f: 64.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
          },
          {
            time_epoch: 1601722800,
            time: "2020-10-03 21:00",
            temp_c: 15.7,
            temp_f: 60.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 126,
            wind_dir: "SE",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 67,
            cloud: 0,
            feelslike_c: 15.7,
            feelslike_f: 60.3,
            windchill_c: 15.7,
            windchill_f: 60.3,
            heatindex_c: 17.7,
            heatindex_f: 63.9,
            dewpoint_c: 18.9,
            dewpoint_f: 66.0,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
          },
          {
            time_epoch: 1601726400,
            time: "2020-10-03 22:00",
            temp_c: 18.4,
            temp_f: 65.1,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 129,
            wind_dir: "SE",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 67,
            cloud: 2,
            feelslike_c: 18.4,
            feelslike_f: 65.1,
            windchill_c: 18.4,
            windchill_f: 65.1,
            heatindex_c: 20.3,
            heatindex_f: 68.5,
            dewpoint_c: 18.4,
            dewpoint_f: 65.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.8,
            gust_kph: 9.4,
          },
          {
            time_epoch: 1601730000,
            time: "2020-10-03 23:00",
            temp_c: 21.1,
            temp_f: 70.0,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 131,
            wind_dir: "SE",
            pressure_mb: 1015.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 67,
            cloud: 5,
            feelslike_c: 21.1,
            feelslike_f: 70.0,
            windchill_c: 21.1,
            windchill_f: 70.0,
            heatindex_c: 22.9,
            heatindex_f: 73.2,
            dewpoint_c: 17.9,
            dewpoint_f: 64.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.3,
            gust_kph: 6.8,
          },
        ],
      },
    ],
  },
  alert: {},
};
